### PR TITLE
Re-enable PY3

### PR DESCRIPTION
**Pull request by remram44**
This needs to work to build noarch packages (like conda-forge/rpaths-feedstock#1)

### CODE REVIEW

**Comment by isuruf** [comment]
See https://conda-forge.org/docs/conda-forge_gotchas.html#using-a-fork-vs-a-branch-when-updating-a-recipe

**Comment by remram44** [comment]
> Branches are automatically published

That's a huge gotcha. I assumed that, like every software project on GitHub, no deployment is made from branches. There should be a budget warning (PR checklist is too late, branch has been pushed).

Shouldn't matter for this (hopefully?)

**Comment by isuruf** [comment]
> Shouldn't matter for this (hopefully?)

Linux builds have been published, but that's fine for now. Let me know if you want me to delete those.

**Comment by remram44** [comment]
Seemed to work, so having those packages exist shouldn't be a problem. I'm trying to move to noarch anyway (#2, from a fork this time :wink:). Thanks!

**Pull request merged**
